name: conv_onet
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - imageio
  - numpy
  - numpy-base
  - matplotlib
  - matplotlib-base
  - pandas
  - pillow
  - pyembree
  - pytest
  - python=3.6.7
  - pytorch=1.4.0
  - pyyaml
  - scikit-image
  - scipy
  - tensorboardx
  - torchvision
  - tqdm
  - trimesh
  - pip:
    - h5py
    - plyfile
    - torch_scatter

